version: v1.3.1

serve:
  public:
    base_url: http://localhost:4433/
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:5173
        - http://localhost:5000
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://localhost:4434/
    port: 4434

selfservice:
  default_browser_return_url: http://localhost:5173/
  allowed_return_urls:
    - http://localhost:5173/

  methods:
    password:
      enabled: false
    oidc:
      config:
        providers:
          - client_id: CHANGE_ME
            client_secret: CHANGE_ME
            id: github
            label: github
            mapper_url: file:///etc/config/kratos/github.jsonnet
            provider: github-app
            scope: []
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: false
    lookup_secret:
      enabled: false
    link:
      enabled: true
    code:
      enabled: true
    profile:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:5173/auth-error

    settings:
      ui_url: http://localhost:5173/account/profile
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://localhost:5173/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://localhost:5173/verification
      use: code
      after:
        default_browser_return_url: http://localhost:5173/

    logout:
      after:
        default_browser_return_url: http://localhost:5173/

    login:
      ui_url: http://localhost:5173/login
      lifespan: 10m
      after:
        default_browser_return_url: http://localhost:5173/

    registration:
      lifespan: 10m
      ui_url: http://localhost:5173/signup
      after:
        default_browser_return_url: http://localhost:5173/welcome

        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
        oidc:
          hooks:
            - hook: session
            - hook: show_verification_ui
            - hook: web_hook
              config:
                url: http://api.pandaci.com/v1/ory/after/registration
                method: POST
                body: file:///etc/config/kratos/webhook.jsonnet
                response:
                  ignore: true
                auth:
                  type: api_key
                  config:
                    name: Authorization
                    value: Basic PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
                    in: header



log:
  level: info
  format: text
  leak_sensitive_values: false

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 12

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

session:
  cookie:
    domain: localhost

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    from_address: no-reply@pandaci.com
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
